#!/bin/bash
# paccclean (Pacman Cache Cleaner) - removes cached versions of packages that
# have already been uninstalled
#
# Copyright (c) 2013        Valery Kharitonov <kharvd@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

myname=paccclean
version=0.1

usage() {
	cat <<EOF
Pacman Cache Cleaner, version $version

usage: $myname <operation>

$myname (Pacman Cache Cleaner) utility removes cached versions of packages that
have already been uninstalled

  Operations:
    -s, --show      show packages to be removed.
    -r, --remove    remove packages.
    -h, --help      show this message.

Copyright (c) 2013     Valery Kharitonov <kharvd@gmail.com>
EOF
}

show=0
remove=0

if [ $# -ne 1 ]
then
    echo -ne "No operation specified.\nUse -h or --help option to see the list" 
    echo " of available operations."
    exit 0
fi

case $1 in
    -h|--help)
        usage
        exit 0 ;;
    -r|--remove)
        remove=1 ;;
    -s|--show)
        show=1 ;;
    *)
        echo -ne "Invalid operation specified.\nUse -h or --help option to see"
        echo " the list of available operations."
        exit 0 ;;
esac

cached=$(mktemp --tmpdir=.)
installed=$(mktemp --tmpdir=.)
removed=$(mktemp --tmpdir=.)

ls -1 /var/cache/pacman/pkg/ | sed 's/^\(.*\)-[^-]*-[^-]*-[^-]*$/\1/' | sort -u > $cached
pacman -Qq > $installed

while read LINE
do 
    grep -x $LINE $installed > /dev/null
    if [ $? -eq 1 ] 
    then 
        if (( $show ))
        then
            echo $(ls -1 /var/cache/pacman/pkg/$LINE-* | grep -e "$LINE-[0-9]")
        elif (( $remove ))
        then
            rm -v $(ls -1 /var/cache/pacman/pkg/$LINE-* | grep -e "$LINE-[0-9]")
        fi
    fi 
done < $cached

rm $cached $installed
